name: matrix

on: 
  push:

jobs: 
  matrix-job:
    name: matrix job
    strategy:
      matrix: 
        runner: [ubuntu-latest, windows-latest]
        paython-verison: [3.11, 3.12, 3.13]

        include: 
          - runner: macos-lates
            python-version: 3.11
        execlude: 
          - runner: windows-latest
            python-version: 3.12
    runs-on: ${{ matrix.runner }}

      steps:
        run: echo this job will run in python version ${{ matrix.python-version }}
